### ISSUE TITLE
Script Répertoire

### ISSUE THREAD

**Issue by maitrepylos** [KaelyouLife/esa_php#1]
Salut,

Ton exo, tu l'as fais toi même où tu t'es aidé d'un tuto.
Juste pour savoir si tu as compris tout ce que tu as fais, notamment les includes ?

**Comment by maitrepylos** [comment]
Peux-tu aussi faire en sorte que tes répertoire, soit en minuscules, sans accent et sans espaces ?
Merci

**Comment by KaelyouLife** [comment]
Bonjour monsieur,

En ce qui concerne les include, c'est Nathanial qui m'a fait découvrir ça en cours. Comparable (je suppose?) à ce qu'on utilise en python pour séparer nos fonctions. Pour tout le reste je n'ai pas utiliser d'autres supports que votre cours.
Je vais corriger ça.

Merci pour votre retour

**Comment by maitrepylos** [comment]
Dans ce cas, je te conseilles d'aller voir les "require" et "require_once"

**Comment by KaelyouLife** [comment]
Ok je vois la différence, dans le cas d'un plus gros projet je devrais plutôt utiliser require pour mes scripts importants et include pour de la mise en page, ou du moins quelque chose de moins important ?
Dans notre cas je devrais plutôt utiliser require étant donné que c'est mon script principal ?

Merci
